
#   compile and run java code to retrieve swim data

run: classes/com/cssi/CssiConsumer.class
	cd bin && ./doit.sh

classes/com/cssi/CssiConsumer.class: src/main/java/com/cssi/CssiConsumer.java
	../../apache-ant-1.10.5/bin/ant

build:
	../../apache-ant-1.10.5/bin/ant


